name: Docs
on: [push]
jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r docs/requirements-docs.txt
      - name: Build docs
        run: |
          cd docs
          make html
      - name: Archive docs build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docs-build-artifacts
          path: docs/build/html

  docs-deploy:
    needs: docs-build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '8.10.0'
      - name: Download docs build artifacts
        uses: actions/download-artifact@v2
        with:
          name: docs-build-artifacts
      - name: Debug
        run: ls .
      - name: Install and configure dependencies
        run: |
          npm install -g --silent gh-pages@2.0.1
          git config user.email "ci-build@mhmdkanj.com"
          git config user.name "ci-build"
      - name: Deploy docs to GH Pages
        run: gh-pages --dist docs/build/html
