name: Docs
on: [push]
jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r docs/requirements-docs.txt
      - name: Build docs
        run: |
          cd docs
          make html
      - name: Archive docs build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: docs-build-artifacts
          path: html
