name: Inspect
on: [push]
jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install flake8==3.8.4
      - name: Inspect code style
        run: flake8

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements-dev.txt
      - name: Run unit tests
        run: pytest --junitxml=junit/test-results.xml --cov=renamerename --cov-report=xml:coverage.xml --cov-report=term
      - name: Generate coverage report
        run: coverage xml
      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v1
        with:
          files: coverage.xml
